networks:
  sahdoio-network:
    driver: bridge
    ipam:
      driver: default

services:
  sahdoio-nginx:
    container_name: sahdoio-nginx
    image: nginx
    ports:
      - '8000:80'
    depends_on:
      - sahdoio
    volumes:
      - ../src:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sahdoio-network

  sahdoio:
    container_name: sahdoio
    build:
      context: ./
      dockerfile: ./api.Dockerfile
    image: sahdoio
    ports:
      - '9000:9000'
    volumes:
      - ../src:/var/www
    networks:
      - sahdoio-network

  sahdoio-mysql:
    container_name: sahdoio-mysql
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hintify
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
    networks:
      - sahdoio-network

  sahdoio-mongo:
      container_name: sahdoio-mongo
      image: mongo
      ports:
          - 27017:27017
      volumes:
          - ../src:/var/www
      logging:
          driver: none
      networks:
      - sahdoio-network
