version: '3'

networks:
  sahdoio-network:
    driver: bridge
    ipam:
      driver: default

services:
  sahdoio-nginx:
    container_name: sahdoio-nginx
    image: nginx
    ports:
      - '8080:80'
    depends_on:
      - sahdoio
    volumes:
      - ../src:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sahdoio-network

  sahdoio:
    container_name: sahdoio
    build:
      context: ./
      dockerfile: ./app.Dockerfile
    image: sahdoio
    ports:
      - '9000:9000'
    volumes:
      - ../src:/var/www
    networks:
      - sahdoio-network

  sahdoio-nodejs:
    container_name: sahdoio-nodejs
    build:
      context: ./
      dockerfile: ./nodejs.Dockerfile
    image: sahdoio/nodejs
    ports:
      - '5173:5173'
    volumes:
      - ../src:/var/www
    networks:
      - sahdoio-network
